version: "3"

services:

  wiredcraft-api:
    container_name: wiredcraft-api
    image: lerignoux/wiredcraft-test-backend
    networks:
      - wiredcraft
    depends_on:
      - wiredcraft-db
    restart: always
    volumes:
      - "./api:/app"

  wiredcraft-db:
    container_name: wiredcraft-db
    image: cassandra:3.11
    networks:
      - wiredcraft
    restart: always

  wiredcraft-nginx:
    container_name: wiredcraft-nginx
    image: nginx:alpine
    networks:
      - wiredcraft
    depends_on:
      - wiredcraft-api
      - wiredcraft-db
    ports:
      - 1443:443
      - 1080:80
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - /root/data/certificates:/etc/certificates
      - /root/data/dhparam.pem:/etc/ssl/dhparam.pem

networks:
  wiredcraft:
