version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9
      - image: cassandra:3.11
        name: wiredcraft-db
        port: 9042
        environment:
          MAX_HEAP_SIZE: 2048m
          HEAP_NEWSIZE: 512m

    working_directory: ~/api

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm --prefix api install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "api/package.json" }}

      - run:
          name: waiting for The DB to be UP
          command: sleep 20

      - run:
          name: run the tests
          command: npm --prefix api run test
