version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.9

    working_directory: ~

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: build the containers
          command: docker-compose -f docker-compose-test.yml build

      - run:
          name: setup the environement
          command: docker-compose -f docker-compose-test.yml up -d

      - run:
          name: run tests
          command: docker run -it --rm --name wiredcraft-test-backend-tests -v /home/circleci/project/api:/app wiredcraft-api npm run test
